# Generated by Django 5.0.3 on 2024-04-02 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='write_time',
            new_name='due_date',
        ),
    ]
