# Generated by Django 5.0.3 on 2024-04-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_alter_comment_user_alter_reply_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='article',
            new_name='comment',
        ),
    ]
