# Generated by Django 5.0.4 on 2024-04-27 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0012_article_last_viewed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_viewed_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
