# Generated by Django 5.0.4 on 2024-04-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0013_article_last_viewed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
    ]
