# Generated by Django 5.0.3 on 2024-03-28 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='write_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
