# Generated by Django 5.0.3 on 2024-04-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_remove_article_write_date_article_write_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(default='others', max_length=20),
        ),
    ]
